version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    ports:
      - "80:3131"
    container_name: teddy-backend-prod
    image: teddy-backend-image-prod
    command: npm run start
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgress

  postgress:
    image: postgres:15
    container_name: teddy-backend-postgres-prod
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local
